name: example-workflow
on: [push]
jobs:
    hello-world:
        if: github.base_ref == 'main'
        runs-on: ubuntu-latest
        steps:
            - name: "Hello World"
              run: echo "Hello World!"
    goodbye-moon:
        runs-on: ubuntu-latest
        steps:
            - name: "Goodbye Moon"
              run: echo "Goodbye Moon! ${{github.base_ref}}"
